In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

# 导入鸢尾花数据
iris_data = load_iris()
data = iris_data.data
target = iris_data.target
# 划分数据集
X_train, X_test, Y_train, Y_test = train_test_split(
    data,
    target,
    test_size=0.2,
    random_state=1
)

model = GaussianNB()

# 训练
model.fit(X_train, Y_train)
# 测试
print("测试数据预测值：", model.predict(X_test))
print("测试数据实际值：", Y_test)
# 得分
print("训练集上得分为：", model.score(X_train, Y_train))
print("测试集上得分为：", model.score(X_test, Y_test))
# X_test中前五个样本属于每一个类别的概率
print("前五条测试数据属于每个类的概率（保留三位）：\n", np.round(model.predict_proba(X_test[:5]), 3))

# 查看参数
print("class_count_", model.class_count_)
print("class_prior_", model.class_prior_)
print("classes_", model.classes_)
print("var_\n", model.var_)
print("theta_\n", model.theta_)


测试数据预测值： [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 2 0 2 1 0 0 1 2]
测试数据实际值： [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0 1 1 1 0 2 1 0 0 1 2]
训练集上得分为： 0.95
测试集上得分为： 0.9666666666666667
前五条测试数据属于每个类的概率（保留三位）：
 [[1.    0.    0.   ]
 [0.    1.    0.   ]
 [0.    0.977 0.023]
 [1.    0.    0.   ]
 [0.    0.    1.   ]]
class_count_ [39. 37. 44.]
class_prior_ [0.325      0.30833333 0.36666667]
classes_ [0 1 2]
var_
 [[0.10749507 0.13042735 0.02529915 0.01094017]
 [0.274916   0.10651571 0.21344047 0.03943024]
 [0.38642046 0.09204029 0.30315599 0.0788998 ]]
theta_
 [[4.96153846 3.36666667 1.46666667 0.23333333]
 [5.94594595 2.73243243 4.22972973 1.30540541]
 [6.525      2.95227273 5.53409091 2.02045455]]
